### ISSUE TITLE
Post Release TODO, Enhancement Ideas

### ISSUE THREAD

**Issue by saurabhdaware** [saurabhdaware/bsky-widget#2]
Lazy to create separate issues right now so just adding broken things here

## Broken things

- [x] Refactor this ugly codebase (partially done)
- [ ] Preview image in NPM README is broken

## Ideas

- [x] Dark / Dim / Light themes that match bluesky. Even other themes maybe?
- [ ] Option to show posts / pinned post somewhere?
- [x] #10
